name: cron workflow 

on:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/20 1 * * *" 

jobs:
 cron-workflow:
   runs-on: ubuntu-latest
    steps:
      - run: echo "cron workflow"
