name: Second workflow.yml
on: 
    push:
        branches:
            - "main"
jobs:
    first-workflow-job:
        name: first job
        runs-on: ubuntu-latest
        steps:
          - name: checkout steps
            uses: actions/checkout@v3 

          - name: run maven
            uses: mvn clean package
            shell: bash